# Generated by Django 2.1.7 on 2019-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=50)),
                ('accessToken', models.CharField(max_length=50)),
            ],
        ),
    ]
